### ISSUE TITLE
Automatic toogle of publication detail (and others similar)

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#11]
If you go to a publciation detail from a user detailed view clicking on the user publications you go with this link:
http://localhost:3000/public/#/publications/normal/Agreeing%20to%20Agree%3A%20Conflict%20Resolution%20for%20Optimistically%20Replicated%20Data

It would be very good to automatic open it for the user instead forcing to user to open it.

**Comment by inad9300** [comment]
Great idea; in the next commit you should be able to see that change.
