### ISSUE TITLE
Show summary about some stats

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#13]
It should be wonderful to show some stats about the total number of publications, total budget, etc, etc .. at the begining of the listing.

**Comment by inad9300** [comment]
I have included a few of them in the publications (both the scientific ones and the student works) and in projects. Have a look when you can.

**Comment by labkode** [comment]
I took a look I we need to improve two things.
First we should display the summary aligned, both number of projects and total budget should be justified, like a 4 X 4 table.
In the other hand the summary should be dynamic, in you search for some criteria the numbers must change according to this criteria. @inad9300

**Comment by inad9300** [comment]
The fact that they change dynamically is a good idea. I did this, and also changed the statistics into a table, which is semantically more correct, as I see it, achieving by doing this the wanted aligment too. So, this is done.
