### ISSUE TITLE
Show logo alonside/only for partners.

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#14]
For example, inside a reasearch line we should display the logo of the partner instead the name.
Or both like in a caption (logo on top and name below).

**Comment by inad9300** [comment]
This needed to be done for both the members (those not being partners) and the research lines. I preferred putting only the image, and keep the name as a title / tooltip; I think it looks nicer.

**Comment by labkode** [comment]
For members is better show only the names like it is now.

**Comment by inad9300** [comment]
I ment I changed the partner's names for their logos in the member's detailed view.

**Comment by labkode** [comment]
Yes that is ok
