### ISSUE TITLE
When showing funding bodies show the record

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#15]
Instead showing the scope it should be better to show the record for the funding.

**Comment by inad9300** [comment]
I don't manage to get the record for the primary funding body, is it even possible?

**Comment by labkode** [comment]
If the context of a finaced project yes. You can check in admin app updating or creating a financed project.
This info is attached to the financed project, not to the funding body.

**Comment by inad9300** [comment]
Gotcha. Should be done.
