### ISSUE TITLE
Urls in article link don't have http:// only http//

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#17]
Try to click a link under http://localhost:3000/public/#/press

**Comment by inad9300** [comment]
Where exactly did you find such a thing? I wasn't able to find it, even doing a recursive search with grep. Trying to click over the links, except of the fact that some of them doesn't exist, I'm able to properly visit them.

**Comment by labkode** [comment]
To reproduce do the following:
- create an article and put some well formed link
- try to click the link from the press view

**Comment by inad9300** [comment]
Thing is that I cannot access the admin view yet. I'm redirected to http://localhost:3000/instanto_app_admin/login.html and receive a 404 error.

I finally found it; I was doing it wrong in a condition... Now is fixed!
