### ISSUE TITLE
Reduce external dependencies

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#9]
Actually fontawesome.min.css and roboto font are download from external providers.
We should have them locally, it´s true than CDNs can enhance the loading speed but it a security hole as well.

**Comment by inad9300** [comment]
I have solved the _problem_ with FontAwesome. However, it surprised me that the Roboto font was being downloaded from the Google servers; after a search I found that it is a dependency for the Bootstrap theme we are using, Paper. Maybe we can consider changing the theme, but I don't see any advantage on doing this really. Let me know.

**Comment by labkode** [comment]
Maybe it is only a fallback. We should try to put the fonts under fonts and see if it uses the local or the remote one @inad9300

**Comment by inad9300** [comment]
Well, they are directly referrencing the Google source though a CSS `@import`; unless we change this to point to our files, I think there is no any chance for them to be preferred. Any idea?

By the way, I've already downloaded the font and put it in the proper folder just in case we use it in the future.

**Comment by labkode** [comment]
If we have to change it, let´s change it :)

**Comment by inad9300** [comment]
OK then, done!

**Comment by labkode** [comment]
Is difficult to change the import?

**Comment by inad9300** [comment]
Not really. To be totally sure that it will work as expected, I followed the Google source so the only think to do is mimic their file (https://fonts.googleapis.com/css?family=Roboto:300,400,500) with the local URLs.

**Comment by labkode** [comment]
Try this http://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server

**Comment by inad9300** [comment]
That's almost what I did, but using woff and woff2 instead. I think we have enough support with that: http://caniuse.com/#feat=woff. In fact, better than with ttf, which I didn't expect: http://caniuse.com/#search=ttf.

**Comment by labkode** [comment]
Cool. If that worked, you can close this.
